### ISSUE TITLE
Incorrect Dates in rasm dataset

### ISSUE THREAD

**Issue by scaine1** [xray/xray-data#11]
```python
import xarray as xr
ds = xr.tutorial.load_dataset('rasm')
ds
```
#### Expected Output
according to the xarray docs the time output should be 
 * time     (time) datetime64[ns] 1980-09-16T12:00:00 1980-10-17 ...
#### Output of ``xr.show_versions()``

however the results appear to be
  * time     (time) object    1-01-01 00:00:00    1-01-01 00:00:00 ...

This breaks some example that other repos are relying on.

results of xr.shows_versions()

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.11.6.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
LOCALE: en_AU.UTF-8

xarray: 0.10.0
pandas: 0.20.1
numpy: 1.12.1
scipy: 0.19.0
netCDF4: 1.2.8
h5netcdf: None
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.14.3
matplotlib: 2.1.1
cartopy: 0.15.1
seaborn: 0.7.1
setuptools: 27.2.0
pip: 9.0.1
conda: 4.4.9
pytest: 3.0.7
IPython: 5.3.0
sphinx: 1.5.6
</details>?

**Comment by shoyer** [comment]
Can you try updating your environment, particularly pandas and netCDF4? I can't reproduce this wit the latest versions of xarray's dependencies.

**Comment by scaine1** [comment]
just ran a conda update but the issue is still there
results of xr.show_versions() below
<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.11.6.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
LOCALE: en_AU.UTF-8

xarray: 0.10.0
pandas: 0.22.0
numpy: 1.12.1
scipy: 1.0.0
netCDF4: 1.3.1
h5netcdf: None
Nio: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.17.0
matplotlib: 2.1.2
cartopy: 0.15.1
seaborn: 0.8.1
setuptools: 38.4.0
pip: 9.0.1
conda: None
pytest: 3.3.2
IPython: 6.2.1
sphinx: 1.6.6
</details>

**Comment by shoyer** [comment]
OK, I'm stumped. My next best guesses:
- something related the slightly out of date version of NumPy you're using (0.14.0 is the latest release)
- something related to your locale (AU vs US)

That said, I tried to reproduce both of these and failed.

Maybe it's a corrupted download? Try deleting the `.xarray_tutorial_data` folder in your home directory.

**Comment by scaine1** [comment]
deleting the .xarray_tutorial_data fixed the problem! 
it now works for both of my conda envs (the upgraded one and the old one I was using when the issue was reported).
Thanks so much, issue fixed / was not an issue in the first place
